Skip unfound python versions
git-svn-id: https://svn.calendarserver.org/repository/calendarserver/twext/trunk@12381 e27351fd-9f3e-4f54-a53b-843176b1656c

diff --git a/bin/install_pip b/bin/install_pip
--- a/bin/install_pip
+++ b/bin/install_pip
@@ -44,6 +44,11 @@ find_tool ()
 
 for py_version in "2.7" "2.6"; do
 
+    if ! type -p "python${py_version}" > /dev/null; then
+        echo "Python ${py_version} not found.";
+        continue;
+    fi;
+
     easy_install="$(find_tool "easy_install" "${py_version}")";
 
     sudo "${easy_install}" --upgrade setuptools;
