Print cause of `setup.py develop` failures and exit.
git-svn-id: https://svn.calendarserver.org/repository/calendarserver/twext/trunk@12288 e27351fd-9f3e-4f54-a53b-843176b1656c

diff --git a/develop b/develop
--- a/develop
+++ b/develop
@@ -40,7 +40,14 @@ mkdir -p "${dev_libdir}";
 
 export PYTHONPATH="${dev_libdir}:${PYTHONPATH:-}"
 
-cd "${wd}" && ./setup.py develop  \
+cd "${wd}";
+
+if ! ./setup.py develop  \
   --install-dir "${dev_libdir}"   \
   --script-dir "${dev_bindir}"    \
-  > "${dev_root}/setup.log" 2>&1;
+  > "${dev_root}/setup.log" 2>&1; then
+  err=$?;
+  echo "Unable to set up for development:"
+  cat "${dev_root}/setup.log";
+  exit ${err};
+fi;
